export var hello = [
  "hey",
  "hi there",
  "hello there",
  "is anyone there",
  "is anyone here",
  "hi anyone active here",
];
export var siri = [
  "hi siri",
  "hello siri",
  "hey siri",
  "are you siri",
  "is your name siri",
  "i am true",
  "am i right",
  "am i true",
  "i am right",
  "am i okay",
  "is it true",
  "i'm right",
  "i'm right okay",
  "is that true",
  "is this right",
  "are you sure",
  "are you okay",
  "are you fine",
  "is it okay",
  "is it correct",
  "is it posible",
  "is it imposible",
  "is that posible",
  "is this imposible",
  "was this true",
  "had it right",
  "will i go",
  "is it useful",
  "is it",
];
export var name = [
  "what's your name",
  "what is your name",
  "who are you",
  "will you please tell me your name",
  "tell me your name",
  "tell your name",
  "can i ask your name",
  "may i know about yourself",
  "tell about yourself",
  "can i have your address",
  "may i know about you",
];
export var help = [
  "what you can do",
  "what do you do",
  "what you can do for me",
  "what can you do",
  "what can you do for me",
  "what your task",
  "what your ocaption",
  "what's your task",
  "how can you help me",
  "what can you help me",
  "how may you help me",
  "can you help me please",
];
export var who_made_you = [
  "who made you",
  "who has made you",
  "who makes you",
  "who make you",
  "who had made you",
  "what's your developer name",
  "what is your developer name",
  "what is your boss name",
  "what's your boss name",
  "what's the name of your developer",
  "what is the name of your developer",
  "which developer has made you",
  "what's your maker name",
  "who has built you",
  "who build you",
  "who built you",
  "who had built you",
  "who has developed you",
  "who developed you",
  "who had developed you",
  "who developed you",
  "who create you",
  "who has created you",
  "who created you",
  "what's your creators name",
  "what is your creators name",
];

export var feeilings = [
  "how are you",
  "what's up",
  "how is gooing",
  "how are you feeiling",
  "what is your feeiling",
  "how is it going",
];
export var good_night = ["good night siri"];
//export var data = [hello, name, siri, who_made_you, help];
export var commands = [
  hello,
  name,
  siri,
  who_made_you,
  help,
  feeilings,
  good_night,
];
export * from "./__questions__.js";
